# Generated by Django 3.2.6 on 2021-08-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_achievement_staffmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='achievement',
            field=models.CharField(max_length=225),
        ),
    ]
