# Generated by Django 3.2.6 on 2021-08-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_achievement_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='department',
            field=models.CharField(choices=[('Руководство', 'Руководство'), ('Тренерский штаб', 'Тренерский штаб')], max_length=20),
        ),
    ]
