# Generated by Django 3.2.6 on 2021-08-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_staffmember_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='about',
            field=models.TextField(max_length=225),
        ),
    ]
