# Generated by Django 3.2.6 on 2021-08-06 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_rename_staffmember_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='staff_member',
            new_name='employee',
        ),
    ]
