# Generated by Django 3.2.6 on 2021-08-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_rename_staff_member_achievement_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partner',
            new_name='Sponsor',
        ),
    ]
