# Generated by Django 3.2.6 on 2021-08-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_rename_partner_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='born',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
