# Generated by Django 3.2.6 on 2021-08-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_alter_employee_born'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='born',
        ),
    ]
