# Generated by Django 3.2.6 on 2021-08-06 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_remove_employee_born'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='fullName',
        ),
    ]
