# Generated by Django 3.2.6 on 2021-08-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_remove_employee_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
