# Generated by Django 3.2.6 on 2021-08-06 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_auto_20210806_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='fullName',
        ),
    ]
