# Generated by Django 3.2.6 on 2021-08-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_alter_city_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'verbose_name': 'Sponsor or Social Media', 'verbose_name_plural': 'Sponsors & Social Media'},
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Description or URL'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='type',
            field=models.CharField(choices=[('general', 'Генеральный партнер'), ('regular', 'Партнер'), ('social-media', 'Социальная сеть')], max_length=20),
        ),
    ]
