# Generated by Django 3.2.6 on 2021-08-11 14:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_auto_20210810_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('page_reference', models.CharField(choices=[('fanclub', 'Фан-клуб')], max_length=20)),
                ('event_date', models.DateField()),
                ('date_created', models.DateField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Media Album',
                'verbose_name_plural': 'Media Albums',
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.FileField(upload_to='')),
                ('media_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='database.mediaalbum')),
            ],
        ),
    ]
