# Generated by Django 3.2.6 on 2021-08-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_mediaalbum_mediafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(),
        ),
    ]
