# Generated by Django 3.2.6 on 2021-08-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_alter_employee_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
