# Generated by Django 3.2.6 on 2021-08-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_auto_20210813_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Вратарь', 'Вратарь'), ('Защитник', 'Защитник'), ('Нападающий', 'Нападающий')], max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='url',
            field=models.CharField(max_length=100, verbose_name='URL'),
        ),
    ]
