# Generated by Django 3.2.6 on 2021-08-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='line2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Second Line'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='line3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Third Line'),
        ),
    ]
