# Generated by Django 3.2.6 on 2021-08-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_auto_20210816_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='about',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='type',
            field=models.CharField(choices=[('general', 'Генеральный партнер'), ('regular', 'Партнер'), ('MHL2019', 'Партнер чемпионата МХЛ 2019/2020'), ('social-media', 'Социальная сеть')], max_length=20),
        ),
    ]
