# Generated by Django 3.2.6 on 2021-08-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_auto_20210816_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='url',
            field=models.CharField(blank=True, max_length=100, verbose_name='URL'),
        ),
    ]
