# Generated by Django 3.2.6 on 2021-08-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0028_alter_sponsor_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaalbum',
            name='album_description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='mediafile_description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
