# Generated by Django 3.2.6 on 2021-08-17 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_auto_20210817_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('result', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('place', models.IntegerField(choices=[('1', '1 место'), ('2', '2 место'), ('3', '3 место')])),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trophies', to='database.season')),
            ],
            options={
                'verbose_name': 'Trophy',
                'verbose_name_plural': 'Trophies',
            },
        ),
    ]
