# Generated by Django 3.2.6 on 2021-08-17 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0032_auto_20210817_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trophy',
            name='team',
        ),
    ]
