# Generated by Django 3.2.6 on 2021-08-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0034_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
