# Generated by Django 3.2.6 on 2021-08-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0035_alter_rule_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
