# Generated by Django 3.2.6 on 2021-08-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0036_employee_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='order',
            field=models.IntegerField(verbose_name='Webpage order (top to bottom)'),
        ),
    ]
